language: swift
osx_image: xcode9.4

before_install:
  - gem install cocoapods
  - pod repo update --silent
  - gem install xcpretty

script:
  - set -o pipefail && xcodebuild -workspace 'KataScreenshot.xcworkspace'  -scheme 'KataScreenshot' -destination 'platform=iOS Simulator,name=iPhone 8 Plus' build test CODE_SIGN_IDENTITY=- | xcpretty -c
